### ISSUE TITLE
which lidars are supported?

### ISSUE THREAD

**Issue by AndreV84** [NVIDIA-ISAAC-ROS/isaac_ros_map_localization#3]
e.g. for orin devkit
which lidars are supported by the package?
Thanks

**Comment by ashwinvkNV** [comment]
Any lidar that has a ROS driver that publishes flat laser scans to a topic of type [LaserScan.msg](https://github.com/ros2/common_interfaces/blob/humble/sensor_msgs/msg/LaserScan.msg) is supported. You can look at the .msg file for specifications on the input.

We have provided [a node that converts](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/blob/main/isaac_ros_pointcloud_utils/src/laserscan_to_flatscan_node.cpp) from [LaserScan.msg](https://github.com/ros2/common_interfaces/blob/humble/sensor_msgs/msg/LaserScan.msg) to [FlatScan.msg](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/isaac_ros_pointcloud_interfaces/msg/FlatScan.msg). Example [launch file here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/blob/main/isaac_ros_pointcloud_utils/launch/isaac_ros_laserscan_to_flatscan.launch.py).

Also any lidar that produces a 3D point cloud of type [PointCloud2.msg](https://github.com/ros2/common_interfaces/blob/humble/sensor_msgs/msg/PointCloud2.msg) is supported since we provide a cuda accelerated [PointCloud2.msg](https://github.com/ros2/common_interfaces/blob/humble/sensor_msgs/msg/PointCloud2.msg) to [FlatScan.msg](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/isaac_ros_pointcloud_interfaces/msg/FlatScan.msg) converter [node here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/blob/main/isaac_ros_pointcloud_utils/src/pointcloud_to_flatscan_node.cpp).

**Comment by gordongrigor** [comment]
This function has been used with the [SICK Microscan 3](https://www.sick.com/ag/en/safety-laser-scanners/safety-laser-scanners/microscan3/c/g295657) flat laser scan, and 3D LIDAR's [Hesai XT32](https://www.hesaitech.com/product/xt32/) and [Velodyne VLP16](https://velodynelidar.com/products/puck/).
